### ISSUE TITLE
ServiceUnknown org.AGL.afm.user

### ISSUE THREAD

**Issue by zskdan** [iotbzh/afm-widget-examples#1]
Sorry I don't know if this is the right project for creating this issue.
but launching the annex widget with:
`$ dbus-send --session --dest=org.AGL.afm.user --print-reply /org/AGL/afm/user org.AGL.afm.user.start 'string:"webapps-annex@0.0"'`

Gives me : 

`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.AGL.afm.user was not provided by any .service files`

afm-system-daemon, afm-user-daemon and afb-daemon are up and running, and i successfully installed the annex widget with: 

`$ dbus-send --system --dest=org.AGL.afm.system --print-reply /org/AGL/afm/system org.AGL.afm.system.install 'string:{"wgt":"/home/root/annex.wgt","force":true}'`

Any idea ?

**Comment by jobol** [comment]
For the session dbus, the environment variable DBUS_SESSION_BUS_ADDRESS must be set.

I see that you are using the system interface to add widgets. This is no more the way we are processing things. In place, we are using now the session daemon that relay the order. but it is a detail.

**Comment by jobol** [comment]
From your error message, I see that you have set DBUS_SESSION_BUS_ADDRESS but that the destination is not started

Maybe the issue is coming from the fact that DBUS_SESSION_BUS_ADDRESS is pointing a dbus session that is different from the one of the user daemon?

**Comment by zskdan** [comment]
i set the DBUS_SESSION_BUS_ADDRESS through the following command:
`$ eval $(dbus-launch --auto-syntax)`

and DBUS_SESSION_BUS_ADDRESS and DBUS_SESSION_BUS_PID are correctly set.

`$ echo $DBUS_SESSION_BUS_ADDRESS`
`unix:abstract=/tmp/dbus-EEJyeVwbmV,guid=32d18547420a30f94be74b1f56e16277`

 `$ echo $DBUS_SESSION_BUS_PID`
`148`

**Comment by jobol** [comment]
"dbus-launch --auto-syntax" is creating a new instance of dbus-daemon. is this instance only used by afm-user-daemon and dbus-send ?

ps -ef | grep dbus-daemon

**Comment by zskdan** [comment]
`$ps -ef | grep dbus-daemon`
`message+   469     1  0 Mar08 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation`
`root       513   503  0 Mar08 ?        00:00:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation`
`root      1086     1  0 Mar09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session`
`root      1092     1  0 Mar09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session`
`root      1481     1  0 12:03 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session`
`root      1486     1  0 12:03 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session`
`root      1491     1  0 12:03 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 4 --print-address 6 --session`
